name: build tfjs_deno

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Install Dependencies
        run: npm i
      - name: Create Build Directory
        run: mkdir build
      - name: Build tfjs-core
        run: cd tfjs-core && yarn && yarn tsc && yarn bundle && cp ./dist/tf-core.node.js ../build && cp ./dist/tf-core.node.js.map ../build
      - name: Build tfjs-backend-cpu
        run: cd tfjs-backend-cpu && yarn && yarn tsc && yarn build && cp ./dist/tf-backend-cpu.node.js ../build && cp ./dist/tf-backend-cpu.node.js.map ../build
      - name: Build tfjs-backend-webgl
        run: cd tfjs-backend-webgl && yarn && yarn tsc && yarn build && cp ./dist/tf-backend-webgl.node.js ../build && cp ./dist/tf-backend-webgl.node.js.map ../build
      - name: Build tfjs-layers
        run: cd tfjs-layers && yarn && yarn tsc && yarn build && cp ./dist/tf-layers.node.js ../build && cp ./dist/tf-layers.node.js.map ../build
      - name: Build tfjs-data
        run: cd tfjs-data && yarn && yarn tsc && yarn build && cp ./dist/tf-data.node.js ../build && cp ./dist/tf-data.node.js.map ../build
      - name: Build tfjs-converter
        run: cd tfjs-converter && yarn && yarn tsc && yarn build && cp ./dist/tf-converter.node.js ../build && cp ./dist/tf-converter.node.js.map ../build
      - name: Build tfjs-backend-webgpu
        run: cd tfjs-backend-webgpu && yarn && yarn tsc && yarn build && cp ./dist/tf-backend-webgpu.node.js ../build && cp ./dist/tf-backend-webgpu.node.js.map ../build
      - name: Build tfjs
        run: cd tfjs && yarn && yarn build && yarn tsc && cp ./dist/tf.node.js ../build && cp ./dist/tf.node.js.map ../build
      - name: Run Transformer Script
        run: cd build && deno run --allow-read --allow-write https://cdn.discordapp.com/attachments/718805724674785311/848052102689062922/conv.ts
      - name: Push to Deno Branch
        run: |
          cd build
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]" 
          git config --global init.defaultBranch deno
          git init
          git add -A
          git commit -m "ci(deno_build)"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: deno
          directory: build
          force: true
