name: build tfjs_deno

on:
  push:
    branches: [main]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
      - name: Install Dependencies
        run: npm i
      - name: Create Build Directory
        run: mkdir build
      - name: Build tfjs-core
        run: cd tfjs-core && yarn && yarn bundle && cp ./dist/tf-core.node.js ../build
      - name: Build tfjs-backend-cpu
        run: cd tfjs-backend-cpu && yarn && yarn build && cp ./dist/tf-backend-cpu.node.js ../build
      - name: Build tfjs-backend-webgl
        run: cd tfjs-backend-webgl && yarn && yarn build && cp ./dist/tf-backend-webgl.node.js ../build
      - name: Build tfjs-layers
        run: cd tfjs-layers && yarn && yarn build && cp ./dist/tf-layers.node.js ../build
      - name: Build tfjs-data
        run: cd tfjs-data && yarn && yarn build && cp ./dist/tf-data.node.js ../build
      - name: Build tfjs-converters
        run: cd tfjs-converters && yarn && yarn build && cp ./dist/tf-comverters.node.js ../build
      - name: Build tfjs-backend-webgpu
        run: cd tfjs-backend-webgpu && yarn && yarn build && cp ./dist/tf-webgpu.node.js ../build
      - name: Build tfjs
        run: cd tfjs && yarn && yarn build && cp ./dist/tf.node.js ../build
